# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R O O M
email: jonathan@jonathanzong.com
description: >
  An interactive storytelling experience in the browser. COS597C Fall 2015.
  A collaboration of: Savannah Du, Helen Lin, Kathleen Ma, Sarah Wang, Jonathan Zong
baseurl: "/room" # the subpath of your site, e.g. /blog
url: "http://jonathanzong.github.io" # the base hostname & protocol for your site
twitter_username: ohnobackspace
github_username:  jonathanzong

# Build settings
markdown: kramdown
